### PR TITLE
Implement Threads

### PR DESCRIPTION
**Pull request by JohnnyJayJay**
This Pull Request is a draft for the new [threads feature](https://github.com/discord/discord-api-docs/blob/master/docs/topics/Threads.md) in Discord. As with Slash Commands (#64) I would like to use this PR to keep track of the progress and discuss changes and new issues related to this feature as they arise. 

Below is a check list of what needs to be done:

- [x] Define thread endpoints
- [x] Define messaging specs for thread endpoints
- [x] Implement thread endpoints
- [ ] Update the caching middleware to recognise threads
- [ ] Tests
- [x] Update changelog

### CODE REVIEW

**Comment by JohnnyJayJay** [comment]
Summing up today's encountered issues while implementing the endpoints:
- `list-active-threads` returns a 404 Not Found response (I don't know why)
- `join-thread`/`add-thread-members` still use the wrong request method. PUT is documented, but it's actually POST. Apparently, this will still change (discord/discord-api-docs#2978)
- `list-thread-members` does not return an array of thread member objects as documented, but an array of user ids.

**Comment by JohnnyJayJay** [comment]
Issues in the previous message have all been resolved.

**Comment by JohnnyJayJay** [comment]
Caching handlers for threads have been written, but are still untested. I will do this over the next couple of days.

Additionally, a newly discovered bug in the `ready` caching handler has been fixed.
Finally, since this was a fairly small change, I also resolved #55 .

This puts this PR in a good place and it will be ready for review soon.

**Comment by JohnnyJayJay** [comment]
The events are still somewhat confusing. For example, in certain situations, a thread create event is sent when a user is added to a thread (instead of a thread members update event). Sometimes, threads contain members, sometimes they don't, or not all of them. I have yet to figure out what the purpose of `:members` in the thread list sync event is, because so far it has always been empty and on top of that, of the wrong type (it's supposed to be an array, but it's a map). Threads are sometimes marked as locked, but not archived, which should be impossible. 

As it stands right now, the caching middleware caches all information that Discord provides, but the issues are in that information. The thread and especially thread member cache isn't really reliable, but this is something that I can't fix.

**Comment by JohnnyJayJay** [comment]
>    1) Thread List Sync is documented to send down an array but was sending down a map. I'm going to make it consistent with the documentation, was just waiting for Android to roll out but I can do that this week. Sorry about that mixup, probably should have been a map from the start, but I documented it as an array so ...
>   2) I'm going to add back the type field on the create thread without message route but since that wasn't documented, I'll keep it optional and default it to private thread so there's no breaking change
>   3) Eventually adding that /guild/threads route
Otherwise I don't think there are any other thread changes that will happen, we're more in polish / bug fix mode now, not "build even more shit" mode

Update: these changes need to be implemented

**Review by IGJoshua — APPROVED** [review]

**Pull request merged**
